--
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: redis-deployment
    labels:
      type: redis-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        type: redis-app
    template:
      metadata:
        name: redis-pod
        labels:
          type: redis-app
      spec:
        containers:
          - name: myredis
            image: redis
  ...
  