---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: votingapp-deployment
    labels:
      type: voting-app
  spec:
    replicas: 2
    selector:
      matchLabels:
        type: voting-app
    template:
      metadata:
        name: votingapp-pod
        type: voting-app
      spec:
        containers:
          - name: myvotingapp
            image: dockersamples/examplevotingapp_vote
 ...