---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    type: database
spec:
  replicas: 2
  selector:
    matchLabels:
      type: database
  template:
    metadata:
      name: mysql-pod
      labels:
        type: database
    spec:
      containers:
        - name: mydatabase
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: i
...

