---
apiVersion: v1
kind: Pod
metadata: 
  name: mytomee
  namespace: ammunamespace
  labels:
    type: ppp
    author: ammu
spec:
  containers:
    - name: mytomee
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 9999
...
