---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-replicationcontroller
  labels:
    author: Ammu
    type: webserver
spec:
  replicas: 3
  template:
    metadata: 
      name: httpd-pod
      labels:
        type: webserver
        author: ammu
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 9090
...
