---
apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip
  labels:
    type: database
    author: Amaleswari
spec:
  ports:
    - targetPort: 80
      port: 80
  selector:
    type: database
    author: Amaleswari
...

