---
apiVersion: v1
kind: Service
metadata:
  name: tomee-service
  labels:
    type: tomee-service
    author: Ammu
spec: 
   type: LoadBalancer
   ports:
     - targetPort: 8080
       port: 8080
   selector: 
     type: qaserver
     author: Ammu
...


