---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    type: ci-cd
    author: ammu       
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30010
  selector:
      type: ci-cd
      author: Ammu
... 

