---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
  labels: 
    app: mysql
spec: 
  clusterIP: None
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
  selector:
    app: mysql
---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: mysql-deployment
    labels:
      app: mysql
  spec:
    replicas: 2
    serviceName: app-mysql
    selector:
         matchLabels:
           app: mysql
    template:
        metadata:
          name: mysql-pod
          labels:
            app: mysql
        spec:
          containers:
            - name: mydatabase
              image: mysql:5
              ports:
                - name: tcp
                  protocol: TCP
                  containerPort: 3306
              env:
                - name: MYSQL-ROOT_PASSWORD
                  value: Ammu
...
                
