---
version: '3'
services:
  voting-app: 
    image: dockersamples/examplevotingapp_vote
    deploy: 
       replicas: 2
    ports:
     - 5050:80
  myredis:
    image: redis
    ports:
      - 7878:6379
  worker:
    image: dockersamples/examplevotingapp_worker
     
  postgresdatabase:
    image: postgres
    environment:
      POSTGRES_PASSWORD: AMMU
      POSTGRES_USER: SUNNU
      POSTGRES_DB: VENNI

  result-app:
    image: dockersamples/examplevotingapp_result
    ports: 
      - 6060:80
    deploy: 
      replicas: 2
... 
