apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: myredis
  name: myredis
spec:
  ports:
  - name: "7878"
    port: 7878
    targetPort: 6379
  selector:
    io.kompose.service: myredis
status:
  loadBalancer: {}
